exclude: |
  (?x)^(
      \.direnv|
      \.git|
      config|
      run|
      \.lock
  )$
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--enforce-all]
        exclude: tests/models/dsf/data/
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, trunk]
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        language: system
        types: [bash]
        entry: nix develop --command shellcheck
      - id: gitleaks
        name: gitleaks
        language: system
        pass_filenames: false
        entry: nix develop --command gitleaks protect
        args: [--verbose, --redact, --staged]
